### ISSUE TITLE
Alerts editing and viewing

### ISSUE THREAD

**Issue by scheffer78450** [fdebrus/hayward-ha#13]
Hi,

First I would like to say thank you for the great work you have done because now I can completely manage my pool using an Hayward Aqaurite with Home Assistant including lifetime stats hosted in HA and also expose appropriate entities to Apple HomeKit (Temperature, Light, Cover, etc...).

It seems you are not handling and managing Alerts, could it be possible to view it and editing it form HA ?
Attached current Alerts screenshot on the poolwatch.hayward.fr portal.

Thanks in advance.
Regards
Nicolas

<img width="1189" alt="Image" src="https://github.com/user-attachments/assets/fb07759a-8b7c-4205-b07a-1853141cbc1e" />

**Comment by fdebrus** [comment]
I will look at as I reconnect my pool for summer period, everything is shutdown now. 

Quickly looking at, I do not see how to present the data in HA that would have an editable format ? do you have an example from another integration ?

**Comment by fdebrus** [comment]
What will be the purpose of having the edit capabilities in HA ? is it not the type of alerts you set and forget ?

What about moving away from alerts in the Hayward application and instead use HA to alert you ? all those parameters like temperature, redox, etc... are available in HA. You could have automation that trigger and send alert to anything that is connected to HA.

```
description: "Pool Temperature Alert"
mode: single
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.pool_temperature
    above: 28
    below: 24
conditions: []
actions:
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Pool Alert
      title: Pool temperature not within target
```
